fix     fm = currentProgram().getFunctionManager() TypeError: 'ghidra.program.database.ProgramDB' object is not callable
fm = currentProgram().getFunctionManager()
This code will cause the following error:
TypeError: 'ghidra.program.database.ProgramDB' object is not callable

Need to be changed to below:

fm = currentProgram.getFunctionManager()